# Generated by Django 3.2.7 on 2021-09-26 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='data_solicitada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 26, 14, 6, 59, 995266), null=True),
        ),
    ]
