# Generated by Django 3.2.7 on 2021-09-08 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_remove_solicitacoes_status_andamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='data_solicitada',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 8, 19, 13, 23, 460382), null=True),
        ),
    ]
