# Generated by Django 3.2.7 on 2021-09-08 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_alter_solicitacoes_data_solicitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='data_solicitada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 8, 19, 55, 29, 720539), null=True),
        ),
    ]
