# Generated by Django 3.2.7 on 2021-09-15 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0008_alter_solicitacoes_data_solicitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='data_solicitada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 20, 26, 21, 704034), null=True),
        ),
    ]
