# Generated by Django 3.2.7 on 2021-10-05 02:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobreNome', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=usuarios.models.upload_Image_user)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 23, 15, 29, 613583), null=True)),
                ('data_ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
