# Generated by Django 3.2.7 on 2021-09-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='active',
        ),
    ]
