# Generated by Django 3.2.6 on 2021-08-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_administrador_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'adm'), (2, 'usuario')], primary_key=True, serialize=False),
        ),
    ]
