# Generated by Django 3.2.6 on 2021-08-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacoes',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
