# Generated by Django 3.2.7 on 2021-09-08 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0002_alter_reclamacoes_data_reclamacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacoes',
            name='data_reclamacao',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 8, 22, 15, 19, 737073, tzinfo=utc), null=True),
        ),
    ]
