# Generated by Django 3.2.7 on 2021-09-08 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0003_alter_reclamacoes_data_reclamacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacoes',
            name='data_reclamacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 8, 22, 54, 15, 966118, tzinfo=utc), null=True),
        ),
    ]
