# Generated by Django 3.2.7 on 2021-09-08 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0005_alter_reclamacoes_data_reclamacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacoes',
            name='data_reclamacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 8, 19, 55, 29, 717766), null=True),
        ),
    ]
