# Generated by Django 3.2.7 on 2021-09-15 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0007_alter_reclamacoes_data_reclamacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacoes',
            name='data_reclamacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 20, 26, 21, 680355), null=True),
        ),
    ]
