# Generated by Django 3.2.7 on 2021-09-26 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0009_alter_reclamacoes_data_reclamacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacoes',
            name='trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reclamacoes',
            name='data_reclamacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 26, 14, 4, 57, 349035), null=True),
        ),
    ]
