# Generated by Django 3.2.7 on 2021-09-26 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacoes', '0010_auto_20210926_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacoes',
            name='data_reclamacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 26, 14, 6, 59, 993270), null=True),
        ),
    ]
